config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from two_factor.urls import urlpatterns as tf_urls
from two_factor.views import SetupView, LoginView, SetupCompleteView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="open-home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url "admin:index" %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("account/login/", LoginView.as_view(), name="login"),
    path("account/logout/", LogoutView.as_view(), name="logout"),
    path("", include('ehms.core.urls', namespace='ehms-core')),

    # TODO Remove this after make sure that from admin side OTP required is working
    # path("account/two_factor/setup/", SetupView.as_view(), name="setup"),
    # path("account/two_factor/setup/complete/", SetupCompleteView.as_view(), name="setup_complete"),

    path("", include("user_sessions.urls", "user_sessions")),

    # Django Admin, use {% url "admin:index" %}
    path("captcha/", include("captcha.urls")),
    # User management
    # path("accounts/", include("django.contrib.auth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("ehms.core.urls", namespace="core")),
    path("dashboards/", include("ehms.dashboards.urls", namespace="dashboards")),
    path("receptions/", include("ehms.receptions.urls", namespace="receptions")),
    path("patients/", include("ehms.patients.urls", namespace="patients")),
    path("practitioners/", include("ehms.practitioners.urls", namespace="practitioners")),
    path("patients/<int:pk>/medical_sessions/", include("ehms.medical_sessions.urls", namespace="medical_sessions")),
    path("hospitals/", include("ehms.hospitals.urls", namespace="hospitals")),
    path("inventory/", include("ehms.inventory.urls", namespace="inventory")),
    path("queries/", include("ehms.queries.urls", namespace="queries")),
    path("mortuaries/", include("ehms.mortuaries.urls", namespace="mortuaries")),
    path("addresses/", include("ehms.addresses.urls", namespace="addresses")),
    path("family_tree/", include("ehms.family_tree.urls", namespace="family_tree")),
    path("nurses/", include("ehms.nurses.urls", namespace="nurses")),
    path("articles/", include("ehms.articles.urls", namespace="articles")),

    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ehms/core/urls.py
from . import views
from django.urls import path

from .views import WardPractitionerAPIView

app_name = "core"
urlpatterns = [
    path("", view=views.common_home_page, name="home"),
    path(route="api/ward/practitioner/list/", view=WardPractitionerAPIView.as_view(), name="ward-practitioners"),
]

ehms/dashboards/urls.py
from . import views
from django.urls import path

app_name = "dashboards"
urlpatterns = [
    path("country-level/", view=views.country_level_dashboard, name="country-level"),
    path("region-level/", view=views.region_level_dashboard, name="region-level"),
    path("state-level/", view=views.state_level_dashboard, name="state-level"),
    path("district-level/", view=views.district_level_dashboard, name="district-level"),
    path("hospital-level/", view=views.hospital_level_dashboard, name="hospital-level"),
    path("practitioner-level/", view=views.practitioner_level_dashboard, name="practitioner-level"),
    path("nurse-level/", view=views.nurse_level_dashboard, name="nurse-level"),
    path("reception-level/", view=views.reception_level_dashboard, name="reception-level")
    # path("logout/", view=views.logout_user, name="logout"),
]

ehms/hospitals/urls.py
from django.urls import path
from . import views
from .views import ActivityListView, HospitalMedicalSessionListView, HospitalProfileTemplateView

app_name = 'hospitals'
urlpatterns = [
    path(route='dashboard/', view=views.hospital_dashboard, name='hospital-dashboard'),
    path(route='profile/', view=HospitalProfileTemplateView.as_view(), name='profile'),
    path(route='activities/', view=ActivityListView.as_view(), name='activities'),
    path(route='medical_sessions/', view=HospitalMedicalSessionListView.as_view(), name='hospital-medical-sessions')
]

ehms/nurses/urls.py
from . import views
from django.urls import path

app_name = "nurses"
urlpatterns = [
    path(route="", view=views.nurses_in_hospital_list, name="list"),
    path(route="token", view=views.nurse_token_request_page, name="token"),
    path(route="dashboard/", view=views.nurse_dashboard, name="nurse-dashboard"),
    path(route="vital-sign-record/<int:pk>/", view=views.nurse_vital_sign_record, name="vital-sign-record"),
    path(route="vital-sign-record/detail/<int:pk>/", view=views.nurse_vital_sign_record_detail,
         name="vital-sign-record-detail"),
    path(route="intake-output-chart/<int:pk>/", view=views.nurse_intake_output_chart, name="intake-output-chart"),
    path(route="intake-output-chart/detail/<int:pk>/", view=views.nurse_intake_output_chart_detail,
         name="intake-output-chart-detail"),
    path(route="session-notes/<int:pk>/", view=views.nurses_notes, name="session-notes"),
    path(route="session-notes/detail/<int:pk>/", view=views.nurse_notes_detail, name="session-notes-detail"),
    path(route="<int:pk>/", view=views.nurse_profile_page, name="detail"),
]

ehms/queries/urls.py
from django.urls import path
from . import views
from .views import HospitalQueryInboxListView

app_name = 'queries'
urlpatterns = [
    path(
        route='inbox/hospital',
        view=HospitalQueryInboxListView.as_view(),
        name='hospital-inbox'
    ),
    path(
        route='inbox/<int:pk>/practitioner',
        view=views.practitioner_query_inbox,
        name='practitioner-inbox'
    )
]

ehms/activities/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices

from model_utils.models import TimeStampedModel, StatusModel

from ehms.hospitals.models import Hospital
from ehms.patients.models import Patient


class Activity(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Logged in user'), blank=True, null=True,
                                     on_delete=models.RESTRICT, related_name='activity_creator_user')
    activity_level = models.CharField(verbose_name=_('Activity Level'), max_length=200, blank=True, null=True, )
    action = models.CharField(verbose_name=_('Action'), max_length=100, blank=True, null=True, )
    patient = models.ForeignKey(Patient, verbose_name=_('Patient'), blank=True, null=True, on_delete=models.RESTRICT)
    hospital = models.ForeignKey(Hospital, blank=True, null=True, verbose_name=_('Hospital'), on_delete=models.RESTRICT)
    user_group = models.CharField(verbose_name=_('User Group'), max_length=200, blank=True, null=True, )
    uid = models.CharField(verbose_name=_('User UID'), blank=True, null=True, max_length=200)
    description = models.TextField(verbose_name=_('Description of activity'), blank=True, null=True, )
    user_agent = models.TextField(verbose_name=_('User agent'), blank=True, null=True, )
    ip_address = models.CharField(verbose_name=_('IP address'), max_length=200, blank=True, null=True, )
    ip_routable = models.CharField(verbose_name=_('IP routable'), max_length=200, blank=True, null=True, )

    class Meta:
        verbose_name = 'Activity'
        verbose_name_plural = 'Activities'

ehms/addresses/models.py
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.db import models

from model_utils import Choices
from model_utils.models import TimeStampedModel, StatusModel

from ehms.core.utils import verhoeff_random_number


class Country(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(unique=True, verbose_name=_('Name'), max_length=100)
    population = models.BigIntegerField(verbose_name=_('Population'), blank=True, null=True)
    capital = models.CharField(verbose_name=_('Capital'), max_length=100, blank=True, null=True, )
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='country_creator_user')
    uid = models.CharField(verbose_name=_('UID'), max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.uid = verhoeff_random_number(1, 8)
        return super(Country, self).save(*args, **kwargs)


class Region(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=100)
    population = models.BigIntegerField(verbose_name=_('Population'), blank=True, null=True)
    capital = models.CharField(verbose_name=_('Capital'), max_length=100, blank=True, null=True, )
    country = models.ForeignKey(Country, verbose_name=_('Country'), on_delete=models.RESTRICT,
                                related_name="regions_country")
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='region_creator_user')
    uid = models.CharField(verbose_name=_('UID'), max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = _('Region or county')
        verbose_name_plural = _('Regions or counties')

    def __str__(self):
        if self.status == 'active':
            n = f'{self.name}'
        else:
            n = f'{self.name}'
        return f'{n}'

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.uid = verhoeff_random_number(1, 8)
        return super(Region, self).save(*args, **kwargs)


class District(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=100)
    population = models.BigIntegerField(verbose_name=_('Population'), blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=_('Country'), on_delete=models.RESTRICT,
                                related_name='districts_country')
    region = models.ForeignKey(Region, verbose_name=_('Region'), on_delete=models.RESTRICT,
                               related_name="districts_region")
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='district_creator_user')
    uid = models.CharField(verbose_name=_('UID'), max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = _('District')
        verbose_name_plural = _('Districts')

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.uid = verhoeff_random_number(1, 8)
        return super(District, self).save(*args, **kwargs)


class Town(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name of Town'), max_length=100)
    population = models.BigIntegerField(verbose_name=_('Population of Town'), blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=_('Country'), on_delete=models.RESTRICT,
                                related_name="towns_country")
    region = models.ForeignKey(Region, verbose_name=_('Region'), on_delete=models.RESTRICT, related_name="towns_region")
    district = models.ForeignKey(District, verbose_name=_('District'), on_delete=models.RESTRICT,
                                 related_name='towns_district')
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='town_creator_user')
    uid = models.CharField(verbose_name=_('UID'), max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = _('Town or City')
        verbose_name_plural = _('Towns or Cities')

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.uid = verhoeff_random_number(1, 8)
        return super(Town, self).save(*args, **kwargs)


class Postcode(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name of Postcode'), max_length=100)
    population = models.BigIntegerField(verbose_name=_('Population of Postcode'), blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=_('Country'), on_delete=models.RESTRICT,
                                related_name="postcodes_country")
    region = models.ForeignKey(Region, verbose_name=_('Region'), on_delete=models.RESTRICT,
                               related_name="postcodes_region")
    district = models.ForeignKey(District, verbose_name=_('District'), on_delete=models.RESTRICT,
                                 related_name="postcodes_district")
    town = models.ForeignKey(Town, verbose_name=_('Town'), on_delete=models.RESTRICT, related_name="postcodes_town")
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='postcode_creator_user')
    uid = models.CharField(verbose_name=_('UID'), max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = _('Postcode')
        verbose_name_plural = _('Postcodes')

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.uid = verhoeff_random_number(1, 8)
        return super(Postcode, self).save(*args, **kwargs)

ehms/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel, StatusModel

from ehms.addresses.models import Country


class UserProfile(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    GENDER_CHOICES = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
    ADDRESS_CHOICES = [('Temporary', 'Temporary'), ('Permanent', 'Permanent')]

    # Override the status field to set a default value
    status = models.CharField(max_length=20, choices=STATUS, default='active')

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(verbose_name=_('Gender'), choices=GENDER_CHOICES, max_length=6, blank=True)
    date_of_birth = models.DateField(verbose_name=_('Date of Birth'), blank=True, null=True)
    bio = models.TextField(verbose_name=_('Bio'), blank=True)
    designation = models.CharField(max_length=100, verbose_name=_('Designation'), blank=True)
    address_line_1 = models.CharField(verbose_name=_('Address Line 1'), max_length=100,
                                      help_text=_('e.g. Flat No or House No ...'), blank=True)
    address_line_2 = models.CharField(verbose_name=_('Address Line 2'), max_length=200, blank=True,
                                      help_text=_('Extra information related to address e.g. landmark ...'))
    phone = models.CharField(verbose_name=_('Phone'), max_length=10, blank=True)
    alternate_phone = models.CharField(verbose_name=_('Alternative Phone'), max_length=10, blank=True)
    type_of_address = models.CharField(verbose_name=_('Type of address'), choices=ADDRESS_CHOICES, max_length=10,
                                       blank=True)
    remarks = models.TextField(_('Remarks'), max_length=5000, blank=True)
    user_unique_id = models.CharField(max_length=20, blank=True)
    country = models.ForeignKey(Country, verbose_name=_('Country'), on_delete=models.RESTRICT,
                                related_name="users_country", blank=True, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

ehms/templates/nurses/dashboard.html
{% extends "base.html" %}
{% block content %}

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-6">
                <span class="disabled-color pr-5"> Dashboard </span> /
                <a class="pl-5" href="{% url "nurses:detail" nurse.pk %}"> Profile </a> /
                <a class="pl-5" href="{% url "dashboards:nurse-level" %}"> Home </a>
            </div>
            <div class="col-6 d-flex justify-content-end">
            </div>
        </div>
    </div>

    <div class="ehms-hr"></div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-3">
                <div class="card mb-40">
                    <div class="card-header">Total Vital Sign Records</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ total_vsr }}</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="card mb-40">
                    <div class="card-header">Total Input output Chart Records</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ total_ioc }}</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="card mb-40">
                    <div class="card-header">Total notes</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ total_notes }}</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ehms/templates/nurses/nurse_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-6">
                <span class="disabled-color pr-5"> {{ nurse.first_name }} {{ nurse.last_name }} </span> / <a class="pl-5" href="{% url "nurses:list" %}">Nurse List</a>
            </div>

            <div class="col d-flex justify-content-end">

            </div>
        </div>
    </div>

    <div class="ehms-hr"></div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-4">
                <strong>General Section</strong>
                <p class="disabled-text">General information of the nurse</p>
            </div>
            <div class="col-8 form-section">
                <div class="form-section-head">
                    <strong>Nurse General Information</strong>
                </div>
                <form class="A-form" action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-40">
                        <label class="label-box" for="id_uid">UID</label>
                        <input type="text" class="form-control" value="{{ nurse.uid }}" name="uid" id="id_uid">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="">Nurse image</label>
                        <div class="w-100">
                            {% if nurse.image %}
                                <img src="{{ nurse.image_medium.url }}" class="img-fluid slight-round-image" width="200" height="200" alt="{{ nurse.first_name }}-{{ nurse.last_name }}">
                            {% else %} NO PHOTO {% endif %}
                        </div>
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_first_name">First name</label>
                        <input type="text" class="form-control" value="{{ nurse.first_name }}" name="first_name" id="id_first_name">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_middle_name">Middle name</label>
                        <input type="text" class="form-control" value="{{ nurse.middle_name }}" name="middle_name" id="id_middle_name">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_last_name">Last name</label>
                        <input type="text" class="form-control" value="{{ nurse.last_name }}" name="last_name" id="id_last_name">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_date_of_birth">Date of birth</label>
                        <input type="text" class="form-control" value="{{ nurse.date_of_birth }}" name="date_of_birth" id="id_date_of_birth">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_gender">Gender</label>
                        <input type="text" class="form-control" value="{{ nurse.gender }}" name="gender" id="id_gender">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_religion">Religion</label>
                        <input type="text" class="form-control" value="{{ nurse.religion }}" name="religion" id="id_religion">
                    </div>
                </form>
                <div class="button-section text-end">
                    <button type="button" class="ehms-button">Report Changes</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-4">
                <strong>Health Section</strong>
                <p class="disabled-text">Health information of the nurse</p>
            </div>
            <div class="col-8 form-section">
                <div class="form-section-head">
                    <strong>Nurse Health Information</strong>
                </div>
                <form class="A-form" action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-40">
                        <label class="label-box" for="id_blood_group">Blood Group</label>
                        <input type="text" class="form-control" value="{{ nurse.blood_group }}" name="blood_group" id="id_blood_group">
                    </div>
                </form>
                <div class="button-section text-end">
                    <button type="button"  class="ehms-button">Report Changes</button>
                </div>
            </div>
        </div>
    </div>

    <div class="ehms-hr pt-20"></div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
             <div class="col-4">
                <strong>Miscellaneous Section</strong>
                <p class="disabled-text">Miscellaneous information of the nurse</p>
            </div>
            <div class="col-8 form-section">
                <div class="form-section-head">
                    <strong>Nurse Miscellaneous Information</strong>
                </div>
                <form class="A-form" action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-40">
                        <label class="label-box" for="id_remarks">Remarks</label>
                        {% if nurse.remarks %}
                            <textarea class="form-control" rows="5" placeholder="Leave a comment here" id="id_remarks">{{ nurse.remarks }}</textarea>
                        {% else %}
                            <textarea class="form-control disabled-color" rows="5" placeholder="Leave a comment here" id="id_remarks">No remarks yet.</textarea>
                        {% endif %}
                    </div>
                </form>
                <div class="button-section text-end">
                    <button type="button" class="ehms-button">Report Changes</button>
                </div>
            </div>
        </div>
    </div>

    <div class="ehms-hr pt-20"></div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
             <div class="col-4">
                <strong>Address Section</strong>
                <p class="disabled-text">Address information of the nurse</p>
            </div>
            <div class="col-8 form-section">
                <div class="form-section-head">
                    <strong>Nurse Address Information</strong>
                </div>
                <form class="A-form" action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-40">
                        <label class="label-box" for="id_address_line_1">Address Line 1</label>
                        <input type="text" class="form-control" value="{{ nurse.address_line_1 }}" name="address_line_1" id="id_address_line_1">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_address_line_2">Address Line 2</label>
                        <input type="text" class="form-control" value="{{ nurse.address_line_2 }}" name="address_line_2" id="id_address_line_2">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_town">Town</label>
                        <input type="text" class="form-control" value="{{ nurse.town }}" name="town" id="id_town">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_district">District</label>
                        <input type="text" class="form-control" value="{{ nurse.district }}" name="district" id="id_district">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_region">Region</label>
                        <input type="text" class="form-control" value="{{ nurse.region }}" name="region" id="id_region">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_country">Country</label>
                        <input type="text" class="form-control" value="{{ nurse.country }}" name="country" id="id_country">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_phone">Phone</label>
                        <input type="text" class="form-control" value="{{ nurse.phone }}" name="phone" id="id_phone">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_alternate_phone">Alternate Phone</label>
                        <input type="text" class="form-control" value="{{ nurse.alternate_phone }}" name="alternate_phone" id="id_alternate_phone">
                    </div>
                    <div class="mb-40">
                        <label class="label-box" for="id_email">Email</label>
                        <input type="text" class="form-control" value="{{ nurse.email }}" name="email" id="id_email">
                    </div>
                </form>
                <div class="button-section text-end">
                    <button type="button" class="ehms-button">Report Changes</button>
                </div>
            </div>
        </div>
    </div>

    <div class="ehms-hr pt-20"></div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
             <div class="col-4">
                <strong>Hospital Section</strong>
                <p class="disabled-text">Hospital information of the nurse</p>
            </div>
            <div class="col-8 form-section">
                <div class="form-section-head">
                    <strong>Nurse Hospital Information</strong>
                </div>
                <div class="A-form">
                    <div class="div-table">
                        <div class="div-table-row d-flex">
                            <div class="div-table-head flex-fill w-10">Hospital</div>
                            <div class="div-table-head flex-fill w-10">Joined on</div>
                            <div class="div-table-head flex-fill w-10">Relieved on</div>
                            <div class="div-table-head flex-fill w-10">Current Hospital</div>
                        </div>
                        {% for hospital in nurse_hospitals %}
                            <div class="div-table-row d-flex">
                                <div class="div-table-cell flex-fill w-10">{{ hospital.hospital.name }}</div>
                                <div class="div-table-cell flex-fill w-10">{{ hospital.joined_on }}</div>
                                <div class="div-table-cell flex-fill w-10">{{ hospital.relieved_on }}</div>
                                <div class="div-table-cell flex-fill w-10">{{ hospital.current_hospital }}</div>
                            </div>
                        {% empty %}
                            <div class="div-table-row"><div class="div-table-cell flex-fill w-100 text-center">Nothing Found</div></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}