config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from two_factor.urls import urlpatterns as tf_urls
from two_factor.views import SetupView, LoginView, SetupCompleteView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="open-home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url "admin:index" %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("account/login/", LoginView.as_view(), name="login"),
    path("account/logout/", LogoutView.as_view(), name="logout"),
    path("", include('ehms.core.urls', namespace='ehms-core')),

    # TODO Remove this after make sure that from admin side OTP required is working
    # path("account/two_factor/setup/", SetupView.as_view(), name="setup"),
    # path("account/two_factor/setup/complete/", SetupCompleteView.as_view(), name="setup_complete"),

    path("", include("user_sessions.urls", "user_sessions")),

    # Django Admin, use {% url "admin:index" %}
    path("captcha/", include("captcha.urls")),
    # User management
    # path("accounts/", include("django.contrib.auth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("ehms.core.urls", namespace="core")),
    path("dashboards/", include("ehms.dashboards.urls", namespace="dashboards")),
    path("receptions/", include("ehms.receptions.urls", namespace="receptions")),
    path("patients/", include("ehms.patients.urls", namespace="patients")),
    path("practitioners/", include("ehms.practitioners.urls", namespace="practitioners")),
    path("patients/<int:pk>/medical_sessions/", include("ehms.medical_sessions.urls", namespace="medical_sessions")),
    path("hospitals/", include("ehms.hospitals.urls", namespace="hospitals")),
    path("inventory/", include("ehms.inventory.urls", namespace="inventory")),
    path("queries/", include("ehms.queries.urls", namespace="queries")),
    path("mortuaries/", include("ehms.mortuaries.urls", namespace="mortuaries")),
    path("addresses/", include("ehms.addresses.urls", namespace="addresses")),
    path("family_tree/", include("ehms.family_tree.urls", namespace="family_tree")),
    path("nurses/", include("ehms.nurses.urls", namespace="nurses")),
    path("articles/", include("ehms.articles.urls", namespace="articles")),

    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ehms/core/urls.py
from . import views
from django.urls import path

from .views import WardPractitionerAPIView

app_name = "core"
urlpatterns = [
    path("", view=views.common_home_page, name="home"),
    path(route="api/ward/practitioner/list/", view=WardPractitionerAPIView.as_view(), name="ward-practitioners"),
]

ehms/medical_sessions/urls.py
from . import views
from django.urls import path

app_name = "medical_sessions"
urlpatterns = [
    path(route="", view=views.medical_session_list, name="list"),
    path(route="detail/<str:suid>/", view=views.medical_session_detail, name="detail"),
    path(route="new/", view=views.medical_session_create, name="new"),
    path(route="reception/new/", view=views.reception_medical_session_create, name="reception-new"),
]

ehms/nurses/urls.py
from . import views
from django.urls import path

app_name = "nurses"
urlpatterns = [
    path(route="", view=views.nurses_in_hospital_list, name="list"),
    path(route="token", view=views.nurse_token_request_page, name="token"),
    path(route="dashboard/", view=views.nurse_dashboard, name="nurse-dashboard"),
    path(route="vital-sign-record/<int:pk>/", view=views.nurse_vital_sign_record, name="vital-sign-record"),
    path(route="vital-sign-record/detail/<int:pk>/", view=views.nurse_vital_sign_record_detail,
         name="vital-sign-record-detail"),
    path(route="intake-output-chart/<int:pk>/", view=views.nurse_intake_output_chart, name="intake-output-chart"),
    path(route="intake-output-chart/detail/<int:pk>/", view=views.nurse_intake_output_chart_detail,
         name="intake-output-chart-detail"),
    path(route="session-notes/<int:pk>/", view=views.nurses_notes, name="session-notes"),
    path(route="session-notes/detail/<int:pk>/", view=views.nurse_notes_detail, name="session-notes-detail"),
    path(route="<int:pk>/", view=views.nurse_profile_page, name="detail"),
]

ehms/patients/urls.py
from . import views
from django.urls import path

from .views import PatientListView, PatientReceptionListView

app_name = "patients"
urlpatterns = [
    path("", view=PatientListView.as_view(), name="list"),
    path("reception/list/", view=PatientReceptionListView.as_view(), name="reception-list"),
    path("create/", view=views.patient_create, name="create"),
    path("search/", view=views.patient_search_list, name="search"),
    path("<int:pk>/", view=views.patient_detail, name="detail"),
    path("search/keyword/", view=views.patient_search_by_keyword, name="keyword"),
    path("search/advanced/", view=views.patient_advanced_search_list, name="advanced"),
    path("death-record/<int:pk>", view=views.patient_death_record, name="death-record"),
    path("<int:pk>/address/<int:pa>/edit/", view=views.edit_patient_address, name="edit-address"),
]

ehms/queries/urls.py
from django.urls import path
from . import views
from .views import HospitalQueryInboxListView

app_name = 'queries'
urlpatterns = [
    path(
        route='inbox/hospital',
        view=HospitalQueryInboxListView.as_view(),
        name='hospital-inbox'
    ),
    path(
        route='inbox/<int:pk>/practitioner',
        view=views.practitioner_query_inbox,
        name='practitioner-inbox'
    )
]

ehms/core/models.py
from django.db import models

# Create your models here.

ehms/dashboards/models.py
from django.db import models

# Create your models here.

ehms/patients/models.py
import contextlib
import datetime
import math
import os

from django.conf import settings
from django.db import models, transaction
from django.utils import timezone
from django.utils.datetime_safe import date
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from model_utils import Choices
from model_utils.models import TimeStampedModel, StatusModel
from pilkit.processors import ResizeToFill

from ehms.addresses.models import Country, Region, District, Town, Postcode
from ehms.core.utils import GENDER_CHOICES, RELIGION_CHOICES, MARITAL_CHOICES, PREGNANCY_CHOICES, BLOOD_GROUP_CHOICES, \
    verhoeff_random_number, ADDRESS_CHOICES
from ehms.hospitals.models import Hospital
from ehms.practitioners.models import Practitioner


# TODO: move this to utils
def patient_image_upload(instance, filename):
    now = timezone.now()
    base, extension = os.path.splitext(filename)
    extension = extension.lower()
    return f"patient/images/{now:%Y/%m}/{instance.pk}{extension}"


def patient_document_upload(instance, filename):
    now = timezone.now()
    base, extension = os.path.splitext(filename)
    extension = extension.lower()
    return f"patient/documents/{now:%Y/%m}/{instance.pk}{extension}"


class AgeGroup(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=50, unique=True, )
    range_from = models.IntegerField(verbose_name=_('From'), blank=True, default=0, null=True, )
    range_to = models.IntegerField(verbose_name=_('To'), blank=True, default=0, null=True, )
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='age_group_creator_user')

    class Meta:
        verbose_name = 'Age Group'
        verbose_name_plural = 'Age Groups'

    def __str__(self):
        return f'{self.name}'


class HealthStatus(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=50, unique=True, )
    css_class = models.CharField(verbose_name=_('Class Name'), max_length=100,
                                 help_text='Class name is associated with CSS styles.')
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='health_status_creator_user')

    class Meta:
        verbose_name = 'Health Status'
        verbose_name_plural = 'Health Statuses'

    def __str__(self):
        return f'{self.name}'


class MedicalIllness(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=50, unique=True, )
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='medical_illness_creator_user')

    class Meta:
        verbose_name = 'Medical Illness'
        verbose_name_plural = 'Medical Illnesses'

    def __str__(self):
        return f'{self.name}'


class Allergy(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=50, unique=True, )
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='allergy_creator_user')

    class Meta:
        verbose_name = 'Allergy'
        verbose_name_plural = 'Allergies'

    def __str__(self):
        return f'{self.name}'


class Addiction(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=50, unique=True, )
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='addiction_creator_user')

    class Meta:
        verbose_name = 'Addiction'
        verbose_name_plural = 'Addictions'

    def __str__(self):
        return f'{self.name}'


class Patient(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')

    uid = models.CharField(verbose_name=_('UID'), max_length=255, unique=True, blank=True)
    first_name = models.CharField(verbose_name=_('First Name'), max_length=100, )
    middle_name = models.CharField(verbose_name=_('Middle Name'), max_length=100, blank=True)
    last_name = models.CharField(verbose_name=_('Last Name'), max_length=100, blank=True)
    date_of_birth = models.DateField(verbose_name=_('Date of Birth'))
    birth_time = models.TimeField(verbose_name=_('Birth time'), blank=True, null=True, )
    gender = models.CharField(verbose_name=_('Gender'), choices=GENDER_CHOICES, max_length=11)
    religion = models.CharField(verbose_name=_('Religion'), choices=RELIGION_CHOICES, max_length=50, )
    marital_status = models.CharField(verbose_name=_('Marital status'), choices=MARITAL_CHOICES, max_length=10, )
    pregnancy = models.CharField(verbose_name=_('Pregnancy status'), choices=PREGNANCY_CHOICES, max_length=20, )
    children = models.IntegerField(verbose_name=_('Children'), blank=True, default=0, )
    email = models.EmailField(verbose_name=_('Email'), max_length=100, blank=True, null=True)
    blood_group = models.CharField(verbose_name=_('Blood group'), choices=BLOOD_GROUP_CHOICES, max_length=50,
                                   blank=True)
    height = models.IntegerField(verbose_name=_('Height (in cm)'), blank=True, null=True)
    weight = models.IntegerField(verbose_name=_('Weight (in kg)'), blank=True, null=True)
    disability = models.BooleanField(verbose_name=_('Disability, if any?'), default=False)
    temporary_family_info = models.TextField(verbose_name=_('Temporary family information'), blank=True)
    bcg = models.BooleanField(verbose_name=_('BCG vaccination'), default=False)
    pentavalent = models.BooleanField(verbose_name=_('Pentavalent vaccination'), default=False)
    pneumo = models.BooleanField(verbose_name=_('Pneumo vaccination'), default=False)
    polio = models.BooleanField(verbose_name=_('Polio vaccination'), default=False)
    rotarix = models.BooleanField(verbose_name=_('Rotarix vaccination'), default=False)
    measles_rubella_1 = models.BooleanField(verbose_name=_('Measles Rubella first dose'), default=False)
    measles_rubella_2 = models.BooleanField(verbose_name=_('Measles Rubella second dose'), default=False)
    dpt = models.BooleanField(verbose_name=_('DPT vaccination'), default=False)
    yellow_fever = models.BooleanField(verbose_name=_('Yellow Fever vaccination'), default=False)
    vitamin_a = models.BooleanField(verbose_name=_('Vitamin A vaccination'), default=False)
    tetanus = models.BooleanField(verbose_name=_('Tetanus vaccination'), default=False)
    tt_one_pregnant = models.BooleanField(verbose_name=_('TT1 vaccination'), default=False)
    tt_two_pregnant = models.BooleanField(verbose_name=_('TT2 vaccination'), default=False)
    tt_booster = models.BooleanField(verbose_name=_('TT Booster'), default=False)
    other_information = models.TextField(verbose_name=_('Extra information'), blank=True)
    remarks = models.TextField(verbose_name=_('Remarks'), blank=True)
    vital_status = models.BooleanField(verbose_name=_('Vital status'), default=True)
    voter_card_number = models.CharField(max_length=100, blank=True, )
    hospital = models.ForeignKey(Hospital, verbose_name=_('Hospital'), on_delete=models.RESTRICT,
                                 related_name='patient_hospital')
    health_status = models.ForeignKey(HealthStatus, verbose_name=_('Health Status'), blank=True, null=True,
                                      on_delete=models.RESTRICT, related_name='patient_health_status')
    age_group = models.ForeignKey(AgeGroup, verbose_name=_('Age Group'), on_delete=models.RESTRICT,
                                  related_name='patient_age_group', blank=True, null=True)
    patient_medical_illness = models.ManyToManyField(MedicalIllness, verbose_name=_('Patient medical illness'),
                                                     blank=True, related_name='patient_medical_illness')
    patient_kin_medical_illness = models.ManyToManyField(MedicalIllness, verbose_name=_('Patient kin medical illness'),
                                                         blank=True, related_name='patient_kin_medical_illness')
    patient_allergies = models.ManyToManyField(Allergy, verbose_name=_('Patient medical allergies'), blank=True,
                                               related_name='patient_medical_allergies')
    patient_addictions = models.ManyToManyField(Addiction, verbose_name=_('Patient addictions'), blank=True,
                                                related_name='patient_addictions')
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='patient_creator_user')

    class Meta:
        verbose_name = 'Patient'
        verbose_name_plural = 'Patients'

    def get_full_name(self):

ehms/templates/patients/partial/form-errors.html
{% if patient_form.errors %}
    {% for field in patient_form %}

        {% if field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                <ol>
                {% for error in field.errors %}
                    <li>{{ error|escape }}</li>
                {% endfor %}
                </ol>
            </div>
        {% endif %}
    {% endfor %}

    {% for error in patient_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% if patient_address_form.errors %}
    {% for field in patient_address_form %}

        {% if field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                <ol>
                {% for error in field.errors %}
                    <li>{{ error|escape }}</li>
                {% endfor %}
                </ol>
            </div>
        {% endif %}
    {% endfor %}

    {% for error in patient_address_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

ehms/templates/patients/partial/keyword_search_form.html
 <form id="patient-keyword-search" class="" action="{% url 'patients:keyword' %}" method="GET">
    <div class="div-table">
        <div class="div-table-row d-flex bg-white all-border-radius">
            <div class="div-table-cell flex-fill w-90">
                <div class="form-floating">
                    <select class="form-select border-radius" name="keyword" id="patient_country" aria-label="Keyword" aria-describedby="keyword-search" data-validation="required">
                        <option value="" disabled selected>Choose option</option>
                        {% for keyword in keywords %}
                            <option value="{{ keyword.pk }}">{{ keyword.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="patient_country">Keyword</label>
                </div>
            </div>
            <div class="div-table-cell flex-fill w-10">
                <button type="submit" class="ehms-button-wi border-radius" id="keyword-search">
                    <span class="material-symbols-sharp">search</span>
                </button>
            </div>
        </div>
    </div>
</form>

ehms/templates/patients/partial/keyword_search_list.html
<div class="div-table mt-40">
    <div class="div-table-row d-flex">
        <div class="div-table-head flex-fill w-10">Image</div>
        <div class="div-table-head flex-fill w-30">Name</div>
        <div class="div-table-head flex-fill w-10">Age</div>
        <div class="div-table-head flex-fill w-10">Gender</div>
        <div class="div-table-head flex-fill w-10">Blood Group</div>
        <div class="div-table-head flex-fill w-20">Health Status</div>
        <div class="div-table-head flex-fill w-10">Actions</div>
    </div>
    {% for patient in page_obj %}
        <div class="div-table-row d-flex bg-white">
            <div class="div-table-cell flex-fill w-10">
                {% for image in patient.current_photo %}
                <img class="img-fluid profile-img-rounded health-status-border-{{ patient.health_status.css_class }}" width="50" height="50" src="{{ image.image_thumbnail.url }}" alt="">
                {% empty %} NO PHOTO {% endfor %}
            </div>
            <div class="div-table-cell flex-fill w-30">{{ patient.first_name }} {% if patient.middle_name %} {{ patient.middle_name }} {% endif %} {{ patient.last_name }}</div>
            <div class="div-table-cell flex-fill w-10">{{ patient.age }} </div>
            <div class="div-table-cell flex-fill w-10">{{ patient.gender }} </div>
            <div class="div-table-cell flex-fill w-10">{% if patient.blood_group %} {{ patient.blood_group }} {% else %} {% endif %} </div>
            <div class="div-table-cell flex-fill w-20"><span class="health-status-{{ patient.health_status.css_class }}">{{ patient.health_status.name }}</span></div>
            <div class="div-table-cell flex-fill w-10">
                {# Patient new medical session for practitioner only #}
                {% if request.group_name == 'practitioner level' %}
                    <a href="{% url "medical_sessions:new" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="New Medical Session"><span class="material-symbols-sharp">add_box</span></a>
                {% endif %}
                <a class="pr-10 pl-10" href="{% url "patients:detail" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Patient portfolio"><span class="material-symbols-sharp">account_circle</span></a>
                <a href="{% url "medical_sessions:list" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Medical Sessions"><span class="material-symbols-sharp">ballot</span></a>
            </div>
        </div>
    {% empty %}
        <div class="div-table-row bg-white"><div class="div-table-cell flex-fill w-100 text-center">Nothing Found</div></div>
    {% endfor %}
</div>

ehms/templates/patients/partial/new_patient_address_form.html
<form action="" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="{{ new_patient_address_form.address_line_1.id_for_label }}">{{ new_patient_address_form.address_line_1.label }}</label>
        {{ new_patient_address_form.address_line_1 }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.address_line_2.id_for_label }}">{{ new_patient_address_form.address_line_2.label }}</label>
        {{ new_patient_address_form.address_line_2 }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.phone.id_for_label }}">{{ new_patient_address_form.phone.label }}</label>
        {{ new_patient_address_form.phone }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.alternate_phone.id_for_label }}">{{ new_patient_address_form.alternate_phone.label }}</label>
        {{ new_patient_address_form.alternate_phone }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.type.id_for_label }}">{{ new_patient_address_form.type.label }}</label>
        {{ new_patient_address_form.type }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.current_address.id_for_label }}">{{ new_patient_address_form.current_address.label }}</label>
        <div class="form-check form-switch">{{ new_patient_address_form.current_address }}</div>
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.country.id_for_label }}">{{ new_patient_address_form.country.label }}</label>
        {{ new_patient_address_form.country }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.region.id_for_label }}">{{ new_patient_address_form.region.label }}</label>
        {{ new_patient_address_form.region }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.district.id_for_label }}">{{ new_patient_address_form.district.label }}</label>
        {{ new_patient_address_form.district }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.town.id_for_label }}">{{ new_patient_address_form.town.label }}</label>
        {{ new_patient_address_form.town }}
    </div>
    <div class="mb-3">
        <label for="{{ new_patient_address_form.postcode.id_for_label }}">{{ new_patient_address_form.postcode.label }}</label>
        {{ new_patient_address_form.postcode }}
    </div>
    <div class="mt-30">
        <button type="submit" class="ehms-button w-100" name="new_patient_address_form">Add New Address</button>
    </div>
</form>

ehms/templates/patients/partial/patient-addresses.html
<table class="table align-middle">
    <thead>
        <tr>
            <th>#</th>
            <th>Address</th>
            <th>Type</th>
            <th>Current Address</th>
            {% if patient.hospital == request.hospital %}
                <th>Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for patient_address in patient_addresses %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
                {{ patient_address.address_line_1 }}
                {% if patient_address.address_line_2 %}
                    <br>{{ patient_address.address_line_2 }}
                {% endif %}
                <br>{{ patient_address.town.name }}
                <br>{{ patient_address.district.name }}
                <br>{{ patient_address.region.name }}
                <br>{{ patient_address.country.name }}
                <br>Postcode - {{ patient_address.postcode.name }}
            </td>
            <td>{{ patient_address.type }}</td>
            <td>{{ patient_address.current_address }}</td>
            {% if patient.hospital == request.hospital %}
                <td>
                    <a href="{% url 'patients:edit-address' patient.pk patient_address.pk %}"><span class="material-symbols-sharp" title="Edit Address">edit</span></a>
                </td>
            {% endif %}
        </tr>
    {% empty %}
        <tr><td colspan="3" class="text-center">No address found.</td></tr>
    {% endfor %}
    </tbody>
</table>

ehms/templates/patients/partial/patient-list-table.html
<div class="div-table">
    <div class="div-table-row d-flex">
        <div class="div-table-head flex-fill w-10">Image</div>
        <div class="div-table-head flex-fill w-30">Name</div>
        <div class="div-table-head flex-fill w-10">Age</div>
        <div class="div-table-head flex-fill w-10">Gender</div>
        <div class="div-table-head flex-fill w-10">Blood Group</div>
        <div class="div-table-head flex-fill w-20">Health Status</div>
        <div class="div-table-head flex-fill w-10">Actions</div>
    </div>

    {% for patient in patient_list %}
        <div class="div-table-row d-flex {% if patient.vital_status %}bg-white{% else %}bg-dull{% endif %}">
            <div class="div-table-cell flex-fill w-10">
            {% for row in patient.current_photo  %}
                {% if row.image %}
                    <img class="img-fluid profile-img-rounded health-status-border-{{ patient.health_status.css_class }}" width="50" height="50" src="{{ row.image_thumbnail.url }}" alt="">
                {% else %} NO PHOTO {% endif %}
            {% endfor %}
            </div>
            <div class="div-table-cell flex-fill w-30">{{ patient.first_name }} {% if patient.middle_name %} {{ patient.middle_name }} {% endif %} {{ patient.last_name }}</div>
            <div class="div-table-cell flex-fill w-10">{{ patient.age }} </div>
            <div class="div-table-cell flex-fill w-10">{{ patient.gender }} </div>
            <div class="div-table-cell flex-fill w-10">{% if patient.blood_group %} {{ patient.blood_group }} {% else %} {% endif %} </div>
            <div class="div-table-cell flex-fill w-20">
                {% if patient.health_status %}
                <span class="health-status-{{ patient.health_status.css_class }}">{{ patient.health_status.name }}</span>
                {% else %}
                <span>Not Defined</span>
                {% endif %}
            </div>
            <div class="div-table-cell flex-fill w-10">
                {# Patient new medical session for practitioner only #}
                {% if request.group_name == 'practitioner level' %}
                    <a href="{% url "medical_sessions:new" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="New Medical Session"><span class="material-symbols-sharp">add_box</span></a>
                {% endif %}
                <a class="pr-10 pl-10" href="{% url "patients:detail" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Patient portfolio"><span class="material-symbols-sharp">account_circle</span></a>
                <a href="{% url "medical_sessions:list" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Medical Sessions"><span class="material-symbols-sharp">ballot</span></a>
            </div>
        </div>
    {% empty %}
        <div class="div-table-row bg-white"><div class="div-table-cell flex-fill w-100 text-center">Nothing Found</div></div>
    {% endfor %}
</div>