config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from two_factor.urls import urlpatterns as tf_urls
from two_factor.views import SetupView, LoginView, SetupCompleteView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="open-home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url "admin:index" %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("account/login/", LoginView.as_view(), name="login"),
    path("account/logout/", LogoutView.as_view(), name="logout"),
    path("", include('ehms.core.urls', namespace='ehms-core')),

    # TODO Remove this after make sure that from admin side OTP required is working
    # path("account/two_factor/setup/", SetupView.as_view(), name="setup"),
    # path("account/two_factor/setup/complete/", SetupCompleteView.as_view(), name="setup_complete"),

    path("", include("user_sessions.urls", "user_sessions")),

    # Django Admin, use {% url "admin:index" %}
    path("captcha/", include("captcha.urls")),
    # User management
    # path("accounts/", include("django.contrib.auth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("ehms.core.urls", namespace="core")),
    path("dashboards/", include("ehms.dashboards.urls", namespace="dashboards")),
    path("receptions/", include("ehms.receptions.urls", namespace="receptions")),
    path("patients/", include("ehms.patients.urls", namespace="patients")),
    path("practitioners/", include("ehms.practitioners.urls", namespace="practitioners")),
    path("patients/<int:pk>/medical_sessions/", include("ehms.medical_sessions.urls", namespace="medical_sessions")),
    path("hospitals/", include("ehms.hospitals.urls", namespace="hospitals")),
    path("inventory/", include("ehms.inventory.urls", namespace="inventory")),
    path("queries/", include("ehms.queries.urls", namespace="queries")),
    path("mortuaries/", include("ehms.mortuaries.urls", namespace="mortuaries")),
    path("addresses/", include("ehms.addresses.urls", namespace="addresses")),
    path("family_tree/", include("ehms.family_tree.urls", namespace="family_tree")),
    path("nurses/", include("ehms.nurses.urls", namespace="nurses")),
    path("articles/", include("ehms.articles.urls", namespace="articles")),

    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ehms/core/urls.py
from . import views
from django.urls import path

from .views import WardPractitionerAPIView

app_name = "core"
urlpatterns = [
    path("", view=views.common_home_page, name="home"),
    path(route="api/ward/practitioner/list/", view=WardPractitionerAPIView.as_view(), name="ward-practitioners"),
]

ehms/hospitals/urls.py
from django.urls import path
from . import views
from .views import ActivityListView, HospitalMedicalSessionListView, HospitalProfileTemplateView

app_name = 'hospitals'
urlpatterns = [
    path(route='dashboard/', view=views.hospital_dashboard, name='hospital-dashboard'),
    path(route='profile/', view=HospitalProfileTemplateView.as_view(), name='profile'),
    path(route='activities/', view=ActivityListView.as_view(), name='activities'),
    path(route='medical_sessions/', view=HospitalMedicalSessionListView.as_view(), name='hospital-medical-sessions')
]

ehms/medical_sessions/urls.py
from . import views
from django.urls import path

app_name = "medical_sessions"
urlpatterns = [
    path(route="", view=views.medical_session_list, name="list"),
    path(route="detail/<str:suid>/", view=views.medical_session_detail, name="detail"),
    path(route="new/", view=views.medical_session_create, name="new"),
    path(route="reception/new/", view=views.reception_medical_session_create, name="reception-new"),
]

ehms/nurses/urls.py
from . import views
from django.urls import path

app_name = "nurses"
urlpatterns = [
    path(route="", view=views.nurses_in_hospital_list, name="list"),
    path(route="token", view=views.nurse_token_request_page, name="token"),
    path(route="dashboard/", view=views.nurse_dashboard, name="nurse-dashboard"),
    path(route="vital-sign-record/<int:pk>/", view=views.nurse_vital_sign_record, name="vital-sign-record"),
    path(route="vital-sign-record/detail/<int:pk>/", view=views.nurse_vital_sign_record_detail,
         name="vital-sign-record-detail"),
    path(route="intake-output-chart/<int:pk>/", view=views.nurse_intake_output_chart, name="intake-output-chart"),
    path(route="intake-output-chart/detail/<int:pk>/", view=views.nurse_intake_output_chart_detail,
         name="intake-output-chart-detail"),
    path(route="session-notes/<int:pk>/", view=views.nurses_notes, name="session-notes"),
    path(route="session-notes/detail/<int:pk>/", view=views.nurse_notes_detail, name="session-notes-detail"),
    path(route="<int:pk>/", view=views.nurse_profile_page, name="detail"),
]

ehms/patients/urls.py
from . import views
from django.urls import path

from .views import PatientListView, PatientReceptionListView

app_name = "patients"
urlpatterns = [
    path("", view=PatientListView.as_view(), name="list"),
    path("reception/list/", view=PatientReceptionListView.as_view(), name="reception-list"),
    path("create/", view=views.patient_create, name="create"),
    path("search/", view=views.patient_search_list, name="search"),
    path("<int:pk>/", view=views.patient_detail, name="detail"),
    path("search/keyword/", view=views.patient_search_by_keyword, name="keyword"),
    path("search/advanced/", view=views.patient_advanced_search_list, name="advanced"),
    path("death-record/<int:pk>", view=views.patient_death_record, name="death-record"),
    path("<int:pk>/address/<int:pa>/edit/", view=views.edit_patient_address, name="edit-address"),
]

ehms/queries/urls.py
from django.urls import path
from . import views
from .views import HospitalQueryInboxListView

app_name = 'queries'
urlpatterns = [
    path(
        route='inbox/hospital',
        view=HospitalQueryInboxListView.as_view(),
        name='hospital-inbox'
    ),
    path(
        route='inbox/<int:pk>/practitioner',
        view=views.practitioner_query_inbox,
        name='practitioner-inbox'
    )
]

ehms/activities/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices

from model_utils.models import TimeStampedModel, StatusModel

from ehms.hospitals.models import Hospital
from ehms.patients.models import Patient


class Activity(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Logged in user'), blank=True, null=True,
                                     on_delete=models.RESTRICT, related_name='activity_creator_user')
    activity_level = models.CharField(verbose_name=_('Activity Level'), max_length=200, blank=True, null=True, )
    action = models.CharField(verbose_name=_('Action'), max_length=100, blank=True, null=True, )
    patient = models.ForeignKey(Patient, verbose_name=_('Patient'), blank=True, null=True, on_delete=models.RESTRICT)
    hospital = models.ForeignKey(Hospital, blank=True, null=True, verbose_name=_('Hospital'), on_delete=models.RESTRICT)
    user_group = models.CharField(verbose_name=_('User Group'), max_length=200, blank=True, null=True, )
    uid = models.CharField(verbose_name=_('User UID'), blank=True, null=True, max_length=200)
    description = models.TextField(verbose_name=_('Description of activity'), blank=True, null=True, )
    user_agent = models.TextField(verbose_name=_('User agent'), blank=True, null=True, )
    ip_address = models.CharField(verbose_name=_('IP address'), max_length=200, blank=True, null=True, )
    ip_routable = models.CharField(verbose_name=_('IP routable'), max_length=200, blank=True, null=True, )

    class Meta:
        verbose_name = 'Activity'
        verbose_name_plural = 'Activities'

ehms/core/models.py
from django.db import models

# Create your models here.

ehms/dashboards/models.py
from django.db import models

# Create your models here.

ehms/medical_sessions/models.py
import os

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel, StatusModel

from ehms.core.utils import verhoeff_random_number
from ehms.hospitals.models import Hospital
from ehms.patients.models import Patient
from ehms.practitioners.models import Practitioner

# TODO: move to utls
from ehms.utils.helpers import CC


def medical_session_hard_file_upload(instance, filename):
    now = timezone.now()
    base, extension = os.path.splitext(filename)
    extension = extension.lower()
    return f"medical_session/hard_files/{now:%Y/%m}/{instance.pk}{extension}"


def medical_session_supporting_doc_upload(instance, filename):
    now = timezone.now()
    base, extension = os.path.splitext(filename)
    extension = extension.lower()
    return f"medical_session/supporting_documents/{now:%Y/%m}/{instance.pk}{extension}"


class Department(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=100, unique=True)
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='hospital_department_creator_user')
    hospital = models.ForeignKey(Hospital, verbose_name=_('Hospital'), on_delete=models.RESTRICT, )

    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'

    def __str__(self):
        return f'{self.name}'


class Ward(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=100, unique=True)
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='hospital_ward_creator_user')
    hospital = models.ForeignKey(Hospital, verbose_name=_('Hospital'), on_delete=models.RESTRICT, )
    practitioners = models.ManyToManyField('practitioners.Practitioner')

    class Meta:
        verbose_name = 'Ward'
        verbose_name_plural = 'Wards'

    def __str__(self):
        return f'{self.name}'


class Keyword(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    name = models.CharField(verbose_name=_('Name'), max_length=100, unique=True)
    description = models.TextField(verbose_name=_('Description'), blank=True)
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='keyword_creator_user')

    class Meta:
        verbose_name = 'Keyword'
        verbose_name_plural = 'Keywords'

    def __str__(self):
        return f'{self.name}'


class MedicalSession(TimeStampedModel, StatusModel, models.Model):
    STATUS = Choices('active', 'inactive')
    uid = models.CharField(verbose_name=_('UID'), unique=True, max_length=20, blank=True, )
    emergency_session = models.BooleanField(verbose_name=_('Is this an emergency session?'), default=False)
    diagnosis = models.TextField(verbose_name=_('Diagnosis'), blank=True, )
    medication = models.TextField(verbose_name=_('Medication'), blank=True, )
    procedure = models.TextField(verbose_name=_('Procedure'), blank=True, )
    hard_file = models.FileField(verbose_name=_('Hard file upload'), upload_to='medical_sessions/hard_files/',
                                 blank=True, )
    supporting_documents = models.FileField(verbose_name=_('Supporting documents'),
                                            upload_to='medical_session_supporting_doc_upload', blank=True, )
    keywords = models.ManyToManyField(Keyword, )
    hospital = models.ForeignKey(Hospital, verbose_name=_('Hospital'), on_delete=models.RESTRICT, )
    patient = models.ForeignKey(Patient, verbose_name=_('Patient'), on_delete=models.RESTRICT,
                                related_name='medical_session_patient')
    practitioner = models.ForeignKey(Practitioner, verbose_name=_('Practitioner'), on_delete=models.RESTRICT,
                                     related_name='medical_session_practitioner')
    creator_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_('Logged in user'),
                                     on_delete=models.RESTRICT, related_name='medical_session_creator_user', )
    department = models.ForeignKey(Department, verbose_name=_('Department'), on_delete=models.RESTRICT,
                                   related_name='medical_session_department', default='OPD')
    ward = models.ForeignKey(Ward, verbose_name=_('Ward'), on_delete=models.RESTRICT,
                             related_name='medical_session_ward', )
    creation_place = models.CharField(verbose_name=_('Where it is created?'), max_length=100, blank=True)
    ipd_status = models.CharField(verbose_name=_('Patient IPD Status'), choices=CC.IPD_MEDICAL_SESSION_STATUS,
                                  default="Not Applicable", max_length=20)

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.uid = verhoeff_random_number(1, 20)
        return super(MedicalSession, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Medical Session'
        verbose_name_plural = 'Medical Sessions'

    def __str__(self):
        return f'{self.uid}'

ehms/family_tree/forms.py
import re

from django import forms
from captcha.fields import CaptchaField

from ehms.core.utils import RELATIONS


class FamilyRelationForm(forms.Form):
    """
    Family Relation form to create relation between the patients
    """
    first_patient = forms.RegexField(
        label='First Patient',
        error_messages={
            'required': 'First patient UID is required.',
            'invalid': 'First patient UID is invalid'
        },
        strip=True,
        regex=re.compile(r'^\d{12}$'),
    )

    first_to_second_relation = forms.ChoiceField(
        label='First patient relation to second patient',
        widget=forms.Select,
        error_messages={
            'required': 'Choose relation between first to second patient.',
            'invalid': 'Your choice is invalid.'
        },
        choices=RELATIONS,
    )

    second_patient = forms.RegexField(
        label='Second Patient',
        error_messages={
            'required': 'Second patient UID is required.',
            'invalid': 'Second patient UID is invalid'
        },
        strip=True,
        regex=re.compile(r'^\d{12}$'),
    )

    second_to_first_relation = forms.ChoiceField(
        label='Second patient relation to first patient',
        widget=forms.Select,
        error_messages={
            'required': 'Choose relation between second to first patient.',
            'invalid': 'Your choice is invalid.'
        },
        choices=RELATIONS,
    )

    first_patient.widget.attrs.update({
        'class': 'form-control', 'placeholder': 'Enter first patient UID',
        'data-validation': 'required'
    })
    second_patient.widget.attrs.update({
        'class': 'form-control', 'placeholder': 'Enter second patient UID',
        'data-validation': 'required'
    })
    first_to_second_relation.widget.attrs.update({
        'class': 'form-select', 'data-validation': 'required'
    })
    second_to_first_relation.widget.attrs.update({
        'class': 'form-select', 'data-validation': 'required'
    })

ehms/templates/medical_sessions/medical_session_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col">
                New Medical Session /
                <a href="{% url 'patients:detail' patient.pk %}">
                    {{ patient.first_name }} {{ patient.last_name }}
                </a> /
                <a  class="pl-5"
                    href="{% url 'hospitals:hospital-medical-sessions' %}">
                    Medical Session List
                </a>
            </div>
            <div class="col d-flex justify-content-end">
                <a  href="{% url 'medical_sessions:list' patient.pk %}"
                    data-bs-toggle="tooltip"
                    data-bs-placement="top"
                    title="Medical sessions of {{ patient.first_name }} {{ patient.last_name }}">
                    <span class="material-symbols-sharp">list_alt</span>
                </a>
            </div>
        </div>
    </div>

    <div class="ehms-hr"></div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col">
                <form action="" method="POST" enctype='multipart/form-data' id="medical-session-form">
                    {% csrf_token %}
                    <input type="hidden" name="medical_session_form" value="1">
                    <div class="row">
                        <div class="col-6 mb-40">
                            <label class="form-label label-box">{{ medical_session_form.emergency_session.label }}</label>
                            <label class="form-label" for="{{ medical_session_form.emergency_session.id_for_label }}" tabindex="1">
                                <p>Click to check or uncheck</p>
                                {{ medical_session_form.emergency_session }}
                            </label>
                            {{ medical_session_form.emergency_session.errors }}
                        </div>
                        <div class="col-12 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.diagnosis.id_for_label }}">
                                {{ medical_session_form.diagnosis.label }}
                            </label>
                            {{ medical_session_form.diagnosis }}
                        </div>
                        <div class="col-12 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.medication.id_for_label }}">
                                {{ medical_session_form.medication.label }}
                            </label>
                            {{ medical_session_form.medication }}
                        </div>
                        <div class="col-12 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.procedure.id_for_label }}">
                                {{ medical_session_form.procedure.label }}
                            </label>
                            {{ medical_session_form.procedure }}
                        </div>
                        <div class="col-6 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.hard_file.id_for_label }}">
                                {{ medical_session_form.hard_file.label }}
                            </label>
                            {{ medical_session_form.hard_file }}
                        </div>
                        <div class="col-6 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.supporting_documents.id_for_label }}">
                                {{ medical_session_form.supporting_documents.label }}
                            </label>
                            {{ medical_session_form.supporting_documents }}
                        </div>
                        <div class="col-6 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.keywords.id_for_label }}">
                                {{ medical_session_form.keywords.label }}
                            </label>
                            {{ medical_session_form.keywords }}
                        </div>
                        <div class="col-6 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.ward.id_for_label }}">
                                {{ medical_session_form.ward.label }}
                            </label>
                            {{ medical_session_form.ward }}
                        </div>
                        <div class="col-6 mb-40">
                            <label class="form-label label-box" for="{{ medical_session_form.department.id_for_label }}">
                                {{ medical_session_form.department.label }}
                            </label>
                            {{ medical_session_form.department }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {# Model trigger button #}
                            <button type="button" class="ehms-button" data-bs-toggle="modal"
                                    data-bs-target="#medical-session-modal-id" onclick="launchMSModel(this)">
                                Preview
                            </button>
                        </div>
                        <div class="col d-flex flex-row-reverse">
                            {# Main submit button #}
                            <button type="submit" class="ehms-button">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content%}

{% block modal %}
<div class="modal fade" id="medical-session-modal-id" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
            <div class="row modal-header mb-2">
                <div class="col-11">
                    <h3>Preview Page</h3>
                </div>
                <div class="col-1 text-center">
                    <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="col-12 red-color">
                    (Read carefully before you submit. Once Submitted can not be changed.)
                </div>
            </div>

            <div class="modal-body medical-session-modal-body">
                <div class="col-12">
                    <h4>Diagnosis</h4>
                    <p id="modal-diagnosis-view"></p>
                </div>
                <div class="col-12">
                    <h4>Medication</h4>
                    <p id="modal-medication-view"></p>
                </div>
                <div class="col-12">
                    <h4>Procedure</h4>
                    <p id="modal-procedure-view"></p>
                </div>
                <div class="col-12">
                    <h4>Medical session hard file</h4>
                    <p id="modal-hard-file-view"></p>
                </div>
                <div class="col-12">
                    <h4>Medical supporting documents</h4>
                    <p id="modal-supporting-docs-view"></p>
                </div>
                <div class="col-12">
                    <h4>Keywords</h4>
                    <p id="modal-keyword-view"></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock modal %}

{% block inline_javascript %}

    <script nonce="{{ request.csp_nonce }}" type="application/javascript">

        $(function() {

            $('#id_keywords').select2();

            function launchMSModel(obj) {
                let form = $('#medical-session-form').serializeArray();
                let keywords = $(".ms-keywords :selected").map(function (i, el) {
                    return $(el).text();
                }).get();

                $('#modal-diagnosis-view').html(form[2].value || "--------");
                $('#modal-medication-view').html(form[3].value || "--------");
                $('#modal-procedure-view').html(form[4].value || "--------");
                $('#modal-hard-file-view').html($('.ms-hard-file').val() || "--------");
                $('#modal-supporting-docs-view').html($('.ms-supporting-docs').val() || "--------");

                if (keywords.length === 0) {
                    $('#modal-keyword-view').html("--------");
                }
                $.each(keywords, function (key, value) {
                    $('#modal-keyword-view').html(key + 1 + ": " + value + '<br>');
                });
            }
        });

</script>

{% endblock inline_javascript %}

ehms/templates/medical_sessions/medical_session_list.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-6">
                <a class="pr-5" href="{% url 'patients:detail' patient.pk %}">{{ patient.first_name }} {{ patient.last_name }}</a> /
                <a class="pl-5" href="{% url "hospitals:hospital-medical-sessions" %}">Medical Sessions</a>
            </div>
            <div class="col-6 d-flex justify-content-end">
                {% if request.user_type == 'practitioner' %}
                    <a href="{% url "medical_sessions:new" patient.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="New Medical Session">
                    <span class="material-symbols-sharp">ballot</span>
                </a>
                {% endif %}

                <div class="dropdown" data-bs-toggle="tooltip" data-bs-placement="top" title="Sort List">
                    <a href="" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="material-symbols-sharp">sort</span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="patient-list-sort-dropdown">
                        <li><a class="dropdown-item" href="{% url 'medical_sessions:list' patient.pk %}?sort=asc">Ascending</a></li>
                        <li><a class="dropdown-item" href="{% url 'medical_sessions:list' patient.pk %}?sort=desc">Descending</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid content-body">
        <div class="row content-body-inner">
            <div class="col-12">
            <div class="div-table">
                <div class="div-table-row d-flex">
                    <div class="div-table-head flex-fill w-10">#</div>
                    <div class="div-table-head flex-fill w-50">Practitioner</div>
                    <div class="div-table-head flex-fill w-30">Date & Time</div>
                    <div class="div-table-head flex-fill w-10">Actions</div>
                </div>
                {% for medical_session in page_obj %}
                    <div class="div-table-row bg-white d-flex">
                        <div class="div-table-cell flex-fill w-10">{{ forloop.counter }}</div>
                        <div class="div-table-cell flex-fill w-50">
                            <a href="{% url 'practitioners:detail' medical_session.practitioner.pk %}" title="{{ medical_session.practitioner.first_name }}'s profile">
                                {{ medical_session.practitioner.first_name }} {{ practitioner_hospital.practitioner.last_name }}
                            </a>
                        </div>
                        <div class="div-table-cell flex-fill w-30">{{ medical_session.created }}</div>
                        <div class="div-table-cell flex-fill w-10">
                            <a href="{% url "medical_sessions:detail" patient.pk medical_session.uid %}" title="View medical session" data-bs-toggle="tooltip" data-bs-placement="top">
                                <span class="material-symbols-sharp">library_books</span>
                            </a>
                        </div>
                    </div>
                {% empty %}
                    <div class="div-table-row bg-white d-flex">
                        <div class="div-table-cell flex-fill w-100 text-center">Nothing Found</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}